name: Generate GitHub Snake Contribution Graph

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */1 * *" # Daily

jobs:
  generate:
    name: Generate and Push Snake Contribution Graph
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate files
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=green&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      - name: Push files to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-snk-contribs-graph-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
